apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-webapp
  template:
    metadata:
      labels:
        app: fastapi-webapp
    spec:
      serviceAccountName: api-sa
      containers:
      - name: fastapi-webapp
        image: tfdevacr001.azurecr.io/fastapi-sample-webapp:latest
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - name: http
          containerPort: 80