apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-webapp
  template:
    metadata:
      labels:
        app: fastapi-webapp
    spec:
      containers:
        - name: fastapi-webapp
          image: hyukjun/fastapi-sample-webapp:c561e5d6a547f641fcdb41e3c73fac62d61cdeec
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - name: http
              containerPort: 8080
          # For Security
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            # readOnlyRootFilesystem: true
          # Check Availability
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /connections/db
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
