apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-webapp
  template:
    metadata:
      labels:
        app: fastapi-webapp
    spec:
      containers:
        - name: fastapi-webapp
          image: hyukjun/fastapi-sample-webapp:89cf1030c6cced0e922f4f43048740ac2d8923b9
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - name: http
              containerPort: 8080
