apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-webapp
  template:
    metadata:
      labels:
        app: fastapi-webapp
    spec:
      containers:
        - name: fastapi-webapp
          image: hyukjun/fastapi-sample-webapp:815aa8618d15358e4e71ff3e83b490bb6ef74576
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - name: http
              containerPort: 80
