apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-webapp
  template:
    metadata:
      labels:
        app: fastapi-webapp
    spec:
      serviceAccountName: api-sa
      containers:
        - name: fastapi-webapp
          image: hyukjun/fastapi-sample-webapp:3f3c97b05fd4a4688eaaaa9cb1f1e7505a0d1f97
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - name: http
              containerPort: 80
