name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login to ACR
      uses: docker/login-action@v3
      with:
        registry: devaksacr001.azurecr.io
        username: ${{ vars.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and Push Docker image to ACR
      uses: docker/build-push-action@v6.9.0
      with:
          context: .
          push: true
          tags: devaksacr001.azurecr.io/fastapi-sample-webapp:latest
