name: Docker Image CI

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch: 

env:
  IMAGE_NAME: fastapi-sample-webapp

jobs:

  Build-And-Push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      id: cache
      with:
        python-version: '3.11.7'
        cache: 'pip' # caching pip dependencies

    - name: Pytest
      run: |
          pip install -r requirements.txt
          pip install pytest
          pytest app/test_rest.py | tee app/test-results.txt

    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-result
        path: app/test-results.txt

      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Docker image to Dockerhub
      uses: docker/build-push-action@v6.9.0
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
    - name: Modify Manifest
      run: |
        yq -i '.spec.template.spec.containers[0].image="${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"' kubernetes/deployment.yaml
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'hyukjuns@github.com'
        git add kubernetes/deployment.yaml
        git commit -m "Update kubernetes/deployment.yaml by GitHub Actions"
        git push
    
    - run: echo cache result -> '${{ steps.cache.outputs.cache-hit }}' # true if cache-hit occurred on the primary key
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.27.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
        channel-id: 'C07T9V22C75'
        # For posting a simple plain text message
        slack-message: "GitHub Action - ${{ github.workflow }} build result: ${{ job.status }}\n Repository: ${{ github.repository }} Actor: ${{ github.actor }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}