name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      id: cp310
      with:
        python-version: '3.11.7'
        cache: 'pip' # caching pip dependencies
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login to ACR
      uses: docker/login-action@v3
      with:
        registry: devaksacr001.azurecr.io
        username: ${{ vars.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and Push Docker image to ACR
      uses: docker/build-push-action@v6.9.0
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: devaksacr001.azurecr.io/fastapi-sample-webapp:${{ github.sha }}
    - run: echo '${{ steps.cp310.outputs.cache-hit }}' # true if cache-hit occurred on the primary key
